name: Node CI

on:
  push:
    paths:
      - 'gh/*'
      - 'src/*'

jobs:
  build:
  runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          BUILD_SCRIPT: npm install && npm run build:gh # The build script the action should run prior to deploying.
