name: Node CI

on:
  [push]
  # push:
  #   paths:
  #     - 'gh/*'
  #     - 'src/*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout
      uses: actions/checkout@master
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}
      # - name: npm install, build
      #   run: |
      #     npm install
      #     npm run build:gh --if-present
      #   env:
      #     NODE_ENV: production

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          BUILD_SCRIPT: npm install && npm run build:gh # The build script the action should run prior to deploying.
